Feature/s2s error reason
PerimeterX/perimeterx-java-sdk pull request #163
Opened 2021-01-21 11:27 UTC by ori-gold-px

2021-01-24 09:34 UTC, shaul-badusa-px requested changes

2021-01-24 09:34 UTC, shaul-badusa-px commented on src/main/java/com/perimeterx/models/PXContext.java
> +        this.s2sErrorReason = reason;
I think that it will be better encapsulated into an object. Then this function will call the ctor of this object.
You are adding 4 members to the pxContext object with the same logic - gather and encapsulate them.

2021-01-24 09:34 UTC, shaul-badusa-px commented on src/main/java/com/perimeterx/http/PXHttpClient.java
>  package com.perimeterx.http;
Great work here!

2021-01-24 09:34 UTC, shaul-badusa-px commented on src/main/java/com/perimeterx/http/PXHttpClient.java
> +        pxContext.setS2SErrorInfo(errorReason, String.format("Risk API returned status %d: %s", statusCode, statusMessage), statusCode, statusMessage);
Here for example you could just pass the object (My comment about encapsulation)

2021-01-24 09:34 UTC, shaul-badusa-px commented on src/main/java/com/perimeterx/http/PXHttpClient.java
> +            pxContext.setS2SErrorInfo(S2SErrorReason.UNABLE_TO_SEND_REQUEST, e.getMessage(), -1, null);
Code duplication (line 152)

2021-01-24 09:34 UTC, shaul-badusa-px commented on src/main/java/com/perimeterx/internals/PXS2SValidator.java
> +    private void updateContext(PXContext pxContext, RiskResponse response) {
updateContextFromResponse ?

2021-01-24 09:34 UTC, shaul-badusa-px commented on src/main/java/com/perimeterx/internals/PXS2SValidator.java
> +    private boolean isResponseInvalid(RiskResponse response) {
I usually prefer the positive approach (isResponeValid) because true will be a good thing and it's more natural.
What do you think?

2021-01-24 09:34 UTC, shaul-badusa-px commented on src/main/java/com/perimeterx/internals/PXS2SValidator.java
> +            return true;
what the boolean stand for? true is fail?

2021-01-24 10:07 UTC, ori-gold-px commented on src/main/java/com/perimeterx/models/risk/S2SErrorReason.java
> +    public String value;
Done!

2021-01-24 11:00 UTC, ori-gold-px commented on src/main/java/com/perimeterx/http/PXHttpClient.java
> +        pxContext.setS2SErrorInfo(errorReason, String.format("Risk API returned status %d: %s", statusCode, statusMessage), statusCode, statusMessage);
Done!

2021-01-24 11:00 UTC, ori-gold-px commented on src/main/java/com/perimeterx/http/PXHttpClient.java
>  package com.perimeterx.http;
Thank you :)

2021-01-24 11:54 UTC, ori-gold-px commented on src/main/java/com/perimeterx/internals/PXS2SValidator.java
> +    private boolean isResponseInvalid(RiskResponse response) {
That's what I did originally, but it's always used as `!isResponseValid()` so the IDE suggested I change it. I agree with you, though, so I'll change it back.

2021-01-24 11:54 UTC, ori-gold-px commented on src/main/java/com/perimeterx/internals/PXS2SValidator.java
> +            return true;
`true` is to pass the request.

2021-01-24 11:59 UTC, ori-gold-px commented on src/main/java/com/perimeterx/internals/PXS2SValidator.java
> +    private void updateContext(PXContext pxContext, RiskResponse response) {
Done

2021-01-24 11:59 UTC, ori-gold-px commented on src/main/java/com/perimeterx/http/PXHttpClient.java
> +            pxContext.setS2SErrorInfo(S2SErrorReason.UNABLE_TO_SEND_REQUEST, e.getMessage(), -1, null);
Done

2021-01-24 12:00 UTC, ori-gold-px commented on src/main/java/com/perimeterx/models/PXContext.java
> +        this.s2sErrorReason = reason;
I removed this function entirely so now we just have a setter for the new object type.

2021-01-25 08:54 UTC, shaul-badusa-px approved these changes

2021-01-25 08:56 UTC, merged