[SDKNEW-1654] Feature/new block page
PerimeterX/perimeterx-java-sdk pull request #202
Opened 2022-02-24 07:14 UTC by ori-gold-px

https://perimeterx.atlassian.net/browse/SDKNEW-1654

2022-03-01 16:24 UTC, AsafAklerPX commented on src/main/java/com/perimeterx/api/blockhandler/templates/TemplateFactory.java
> +        props.put("logoVisibility", pxConfig.getCustomLogo() == null ? "hidden" : "visible");
No need for logo visibility any more..

2022-03-01 16:26 UTC, AsafAklerPX commented on src/main/resources/com/perimeterx/api/blockhandler/templates/block_template.mustache
> +                Reference ID: #{{uuid}}
we removed the refId don't we? why adding uuid here?

2022-03-01 16:31 UTC, AsafAklerPX commented on src/test/resources/block.mustache
> +                Reference ID: #{{uuid}}
reference id?

2022-03-01 16:32 UTC, AsafAklerPX requested changes
refrence id? also

2022-03-02 10:25 UTC, ori-gold-px commented on src/main/java/com/perimeterx/api/blockhandler/templates/TemplateFactory.java
> +        props.put("logoVisibility", pxConfig.getCustomLogo() == null ? "hidden" : "visible");
Keeping it for hard block page which requires it

2022-03-02 10:25 UTC, ori-gold-px commented on src/main/resources/com/perimeterx/api/blockhandler/templates/block_template.mustache
> +                Reference ID: #{{uuid}}
This is the hard block page -- can't use refId so using uuid instead (same value)

2022-03-02 10:25 UTC, ori-gold-px commented on src/test/resources/block.mustache
> +                Reference ID: #{{uuid}}
They're the same

2022-03-02 11:59 UTC, AsafAklerPX approved these changes

2022-03-02 12:00 UTC, merged