SDKNEW-1766/feature - Enable Running the java enforcer from its repo
PerimeterX/perimeterx-java-sdk pull request #209
Opened 2022-03-22 10:20 UTC by etrpx

Created a web module that consumes the enforcer code and enable to running it.

2022-03-22 11:46 UTC, AsafAklerPX commented on web/pom.xml
> +            <version>6.2.7</version>
is it possible to have the version number as variable to avoid duplication?

2022-03-22 12:04 UTC, AsafAklerPX requested changes
Looks good, organised and simple implementation.
I left few comments for you to address.

2022-03-22 12:21 UTC, etrpx commented on web/pom.xml
> +            <version>6.2.7</version>
This can be done with parent child relationship but it is not recommended because it doesn't have a good support in maven.

2022-03-22 12:22 UTC, etrpx commented on web/src/main/java/com/web/IndexServlet.java
> +@WebServlet("/index")
Yes, done.

2022-03-22 12:27 UTC, etrpx commented on web/src/main/java/com/web/Utils.java
> +        final String filePath = getEnforcerConfigPath();
This method generate file path, it will fail only if the project structure will be changed.

2022-03-22 12:28 UTC, etrpx commented on web/src/main/resources/enforcer_config.json
> +{
Aligned to spec as discussed.

2022-03-23 09:04 UTC, AsafAklerPX approved these changes
Approved as enforcer_config handled on a different task

2022-03-23 10:06 UTC, etrpx commented on web/src/main/java/com/web/Utils.java
> +        final String filePath = getEnforcerConfigPath();
I know :)
You'll get an error only if you'll change the file location and it won't be found.
It's something that shouldn't happen and using try catch won't do and if I was to add them it will be inside getEnforcerConfigPath and not outside.
filePath var is outside because I'm using it in the catch.

2022-03-23 12:01 UTC, AsafAklerPX approved these changes
Looks good to me!

2022-03-23 12:06 UTC, AsafAklerPX approved these changes

2022-03-23 12:06 UTC, AsafAklerPX commented on web/src/main/resources/enforcer_config.json
> +  "px_first_party_enabled": true
px_first_party_enabled should be true by default

2022-03-23 12:07 UTC, AsafAklerPX approved these changes

2022-03-23 12:43 UTC, merged