Feature/enforced and monitored routes
PerimeterX/perimeterx-java-sdk pull request #213
Opened 2022-03-28 15:11 UTC by chen-zimmer-px

The monitored and enforced routes by the new functionality.
The new functionality- 
**module mode is monitor:**
Enforced routes are specific routes that should be enforced. Other routes should be monitored.
**module mode is active_blocking:**
Monitored routes are specific routes that should be monitored. Other routes should be enforced.

2022-03-29 09:54 UTC, OmerBacharPX requested changes

2022-03-29 09:54 UTC, OmerBacharPX commented on src/main/java/com/perimeterx/api/verificationhandler/DefaultVerificationHandler.java
> +        if (!verified && (context.isBlocking() || shouldBypassMonitor)) {
I know this is not your change but we always want to refactor thing to make them better - I think that `shouldBypassMonitor` should be combined with the current `isBlocking` function, at least calling `shouldBypassMonitor` from within `isBlocking`, this is all part of understanding if this request should be considered as monitored request or not.

2022-03-29 09:54 UTC, OmerBacharPX commented on src/main/java/com/perimeterx/models/PXContext.java
> +        return !this.isMonitoredRequest;
I think that isBlocking is a bad name, the `verified` variable already tells us if this request should be blocked or not (in general), the value that this function outputs represent if this should be treat as monitor or actual block when decided to be blocked, therefor the variable name is already good enough and we should use it instead.

`isBlocking` is used once other than your usage in `getRiskMode`, I checked this field in other enforcers and it should indicate if risk is in monitor or active blocking per request (exactly what `isMonitoredRequest` represents)

2022-03-29 09:54 UTC, OmerBacharPX commented on src/main/java/com/perimeterx/models/PXContext.java
> +        this.isMonitoredRequest = checkIfMonitorRequest();
make sure that when sent on activities, this field is still called `simulated_block`

2022-03-29 09:54 UTC, OmerBacharPX commented on src/main/java/com/perimeterx/models/PXContext.java
> +        }
This is not clear enough, the configuration with the current implementation only accepts regex expressions, but what if the customer want exact path (we said the customer can also configure `"/profile"` and the Enforcer should treat this is special route only if the path is exactly /profile). In your current impl if the customer want to configure exact /profile he should add to the configuration `^/profile$` (start and ends with /profile).
Moreover, does this library accepts strings as input or it expects regex as input?

I think we should support both string (for exact paths) and regex as input but let's talk about it.

2022-03-31 09:50 UTC, ori-gold-px commented
I would add to the CHANGELOG even now since you're changing this feature. I know we're going to release right after anyway, but it's good practice to make changes to the changelog on every feature add / bugfix so that all changes are accounted for with every PR and we don't have to dig up old history when doing a release.

2022-03-31 09:56 UTC, ori-gold-px requested changes

2022-03-31 09:56 UTC, ori-gold-px commented on pom.xml
> +            <version>1.18.22</version>
Maybe also good to mention in the changelog!

2022-03-31 10:16 UTC, OmerBacharPX approved these changes

2022-03-31 10:17 UTC, ori-gold-px approved these changes
Looks good!

2022-03-31 10:19 UTC, merged