SDKNEW-1747/feature - Implement CI
PerimeterX/perimeterx-java-sdk pull request #222
Opened 2022-04-05 07:00 UTC by etrpx

2022-04-10 09:18 UTC, ori-gold-px requested changes
Looks really good overall! Just a few small fixes here and there and I think it'll be good to go.

2022-04-10 09:18 UTC, ori-gold-px commented on src/main/java/com/perimeterx/models/activities/AdditionalS2SActivity.java
> +    public String username;
why not `rawUsername`?

2022-04-10 09:18 UTC, ori-gold-px commented on src/main/java/com/perimeterx/api/additionals2s/credentialsIntelligence/protocol/V2CIProtocol.java
> +                getEncodedV2Password(normalizedUsername, credentials.getPassword()),
Should be a private implementation detail of `V2CIProtocol`, right?

2022-04-10 09:18 UTC, ori-gold-px commented on src/main/java/com/perimeterx/api/additionals2s/credentialsIntelligence/protocol/V2CIProtocol.java
> +                getV2NormalizedEmailAddress(rawUsername) : rawUsername;
Should be a private implementation detail of `V2CIProtocol`, right?

2022-04-10 09:18 UTC, ori-gold-px commented on src/main/java/com/perimeterx/api/additionals2s/credentialsIntelligence/loginresponse/LoginResponseCustomCallbackValidator.java
> +        this.customCallback = configuration.getLoginResponseValidationCustomCallback();
Not via JSON, but rather by setting a Java function in the builder

2022-04-10 09:18 UTC, ori-gold-px commented on src/main/java/com/perimeterx/api/additionals2s/credentialsIntelligence/loginrequest/RequestBodyExtractor.java
> +    }
Why query params? The name here is misleading. I would opt for "urlencoded" or something along those lines

2022-04-10 09:18 UTC, ori-gold-px commented on src/main/java/com/perimeterx/api/additionals2s/credentialsIntelligence/loginrequest/RequestBodyExtractor.java
> +            }
I'd confirm the content type is `application/json` before -- what if it's XML?

2022-04-10 09:18 UTC, ori-gold-px commented on src/main/java/com/perimeterx/api/additionals2s/credentialsIntelligence/AdditionalS2SContext.java
> +    public AdditionalS2SContext(HttpServletRequest request, PXConfiguration configuration) throws PXException {
Why do we need this AdditionalS2SContext rather than just saving the loginCredentials on the PXContext directly?

2022-04-10 09:18 UTC, ori-gold-px commented on src/main/java/com/perimeterx/api/PerimeterX.java
> +                final LoginResponseValidatorFactory factory = new LoginResponseValidatorFactory();
Possible to create this once on initialization rather than on each request?

2022-04-10 09:18 UTC, ori-gold-px commented on src/main/java/com/perimeterx/api/additionals2s/CredentialsIntelligenceManager.java
> +    }
Possible to create one on initialization rather than one for every request?

2022-04-10 21:26 UTC, etrpx reviewed
@ori-gold-px , thanks for the thorough review.
I've implemented some of your comments and replied on the rest, please review and let me know if you have any questions.

2022-04-10 21:26 UTC, etrpx commented on src/main/java/com/perimeterx/api/additionals2s/credentialsIntelligence/AdditionalS2SContext.java
> +    public AdditionalS2SContext(HttpServletRequest request, PXConfiguration configuration) throws PXException {
Same as answered above, because this is the infra for additional context such as GraphQL

2022-04-10 21:26 UTC, etrpx commented on src/main/java/com/perimeterx/api/additionals2s/credentialsIntelligence/loginrequest/RequestBodyExtractor.java
> +            }
But we said we're supporting only 3 content types (not including XML).

2022-04-10 21:26 UTC, etrpx commented on src/main/java/com/perimeterx/api/additionals2s/credentialsIntelligence/loginrequest/RequestBodyExtractor.java
> +    }
I don't think so, the name implies how the fields structured: field1={value}&field2={value}

2022-04-10 21:26 UTC, etrpx commented on src/main/java/com/perimeterx/api/additionals2s/credentialsIntelligence/loginresponse/LoginResponseCustomCallbackValidator.java
> +        this.customCallback = configuration.getLoginResponseValidationCustomCallback();
Right, after speaking with @OmerBacharPX I removed it entirely and went with another solution of default value, please review this again together with credentialsCustomExtractor.

2022-04-10 21:26 UTC, etrpx commented on src/main/java/com/perimeterx/api/additionals2s/credentialsIntelligence/protocol/V2CIProtocol.java
> +                getV2NormalizedEmailAddress(rawUsername) : rawUsername;
What do you mean?

2022-04-10 21:26 UTC, etrpx commented on src/main/java/com/perimeterx/api/additionals2s/credentialsIntelligence/protocol/V2CIProtocol.java
> +                getEncodedV2Password(normalizedUsername, credentials.getPassword()),
What do you mean?

2022-04-10 21:26 UTC, etrpx commented on src/main/java/com/perimeterx/models/PXContext.java
> +        return this.pxde != null && this.pxdeVerified && this.pxde.has(BREACHED_ACCOUNT_KEY_NAME);
Why? this is not how it's done in cloudFlare so looks like one is the only option.

2022-04-10 21:26 UTC, etrpx commented on src/main/java/com/perimeterx/models/configuration/credentialsIntelligenceconfig/CILoginMap.java
> +            return Collections.EMPTY_LIST;
Good point, I consulted with @OmerBacharPX  and we decided that the better experience is failure on run time and not in implementation. Let me know if you think otherwise.

2022-04-10 21:26 UTC, etrpx commented on src/main/java/com/perimeterx/models/configuration/credentialsIntelligenceconfig/LoginCredentialsConfig.java
> +    private Function<HttpServletRequest,LoginCredentials> customCallback;
Removed this one, see new implementation.

2022-04-10 21:26 UTC, etrpx commented on src/main/java/com/perimeterx/models/httpmodels/Additional.java
> +    @JsonInclude(JsonInclude.Include.NON_NULL)
Include Non Null means to include only fields that are not null.
It supports multipart s2s.

2022-04-10 21:26 UTC, etrpx commented on src/main/java/com/perimeterx/models/httpmodels/Additional.java
> +            final UserLoginData loginCredentials = ctx.getAdditionalS2SContext().getLoginCredentials();
no, you have it covered in the line above: isContainCredentialsIntelligence

2022-04-10 21:26 UTC, etrpx commented on web/src/main/java/com/web/Config.java
> +    }
This was in the external code wrapping the enforcer.
Anyway it was remove due to new implementation.

2022-04-11 09:54 UTC, ori-gold-px commented on src/main/java/com/perimeterx/api/PerimeterX.java
> +import com.perimeterx.api.additionals2s.credentialsIntelligence.loginresponse.LoginResponseValidatorFactory;
There's a difference between `additionalFields` (the property on the pxContext) and `additional_s2s` (the extra activity that's sent to the collector).

Originally, both CI and GQL were added to the `additionalFields` property since they were going to be just additional fields that we would add on to all activities. (Turns out, both these features are much more complicated than that.)

Only CI uses the `additional_s2s` activity at the moment since its main purpose is to report whether or not the user was able to log in successfully. Not related to GQL at all.

2022-04-11 10:08 UTC, ori-gold-px commented on src/main/java/com/perimeterx/models/httpmodels/Additional.java
> +    @JsonInclude(JsonInclude.Include.NON_NULL)
Not sure what you mean by multipart s2s but only including this field if it's not null is good ✅

2022-04-11 10:09 UTC, ori-gold-px commented on src/main/java/com/perimeterx/models/configuration/credentialsIntelligenceconfig/CILoginMap.java
> +            return Collections.EMPTY_LIST;
There's a log, so I'm good with this 👍

2022-04-11 10:11 UTC, ori-gold-px commented on src/main/java/com/perimeterx/models/activities/AdditionalS2SActivity.java
> +    public String username;
I don't think raw is misleading -- raw meaning not normalized, hashed, or altered in any way

2022-04-11 10:17 UTC, ori-gold-px commented on src/main/java/com/perimeterx/api/additionals2s/credentialsIntelligence/loginrequest/RequestBodyExtractor.java
> +    }
To me, it's very confusing since we're in the RequestBodyExtractor and based on the name, it seems like we're looking at query params when in actuality we're looking at the url-encoded body fields.

2022-04-11 10:18 UTC, ori-gold-px commented on src/main/java/com/perimeterx/api/additionals2s/credentialsIntelligence/loginrequest/RequestBodyExtractor.java
> +            }
Correct, but if it is XML right now we'll try and parse as JSON. This might throw an exception or who knows.

2022-04-11 10:27 UTC, ori-gold-px commented on src/main/java/com/perimeterx/models/PXContext.java
> +        return this.pxde != null && this.pxdeVerified && this.pxde.has(BREACHED_ACCOUNT_KEY_NAME);
At the moment, breached_account is only populated onto the object if it == 1, so right now the check is not necessary.

2022-04-11 10:27 UTC, ori-gold-px commented on src/main/java/com/perimeterx/models/configuration/credentialsIntelligenceconfig/PathType.java
> +
Okay, seems strange to have an enum with only one option but not a big deal

2022-04-11 10:27 UTC, ori-gold-px commented on src/main/java/com/perimeterx/models/httpmodels/Additional.java
> +            final UserLoginData loginCredentials = ctx.getAdditionalS2SContext().getLoginCredentials();
👍

2022-04-11 10:28 UTC, ori-gold-px commented on src/main/java/com/perimeterx/api/additionals2s/credentialsIntelligence/protocol/V2CIProtocol.java
> +                getV2NormalizedEmailAddress(rawUsername) : rawUsername;
Already done 👍

2022-04-11 10:28 UTC, ori-gold-px commented on src/main/java/com/perimeterx/api/additionals2s/credentialsIntelligence/AdditionalS2SContext.java
> +    public AdditionalS2SContext(HttpServletRequest request, PXConfiguration configuration) throws PXException {
That's fine, not a necessary thing to add here but it's fine

2022-04-12 06:55 UTC, ori-gold-px approved these changes
Looks great! If it passed all the E2E and manual tests, it's good to go!

2022-04-12 07:43 UTC, merged