Feature/sdknew 3285 header based logger
PerimeterX/perimeterx-java-sdk pull request #347
Opened 2023-12-08 15:49 UTC by EldarHuman

2023-12-11 22:16 UTC, ori-gold-px requested changes
Looks good! A few recommendations for changes in the comments below.

2023-12-11 22:16 UTC, ori-gold-px commented on src/main/java/com/perimeterx/api/PerimeterX.java
> +                context.logger.sendMemoryLogs(this.configuration, context);
This should happen after the additional s2s activity, no?

2023-12-11 22:16 UTC, ori-gold-px commented on src/main/java/com/perimeterx/api/PerimeterX.java
> +            }
The order of filer phases in JS Core (and the order I recommend) is:

1. First party
2. Filter
3. CORS pre-flight handling (if relevant here)
4. Telemetry

2023-12-25 15:26 UTC, EldarHuman commented on src/main/java/com/perimeterx/utils/logger/LogMemory.java
> +
This is a good idea.
I wasn't aware of that abstract class can be consists of abstract and non-abstract functions. Thanks :)

2023-12-25 15:48 UTC, EldarHuman commented on src/main/java/com/perimeterx/utils/logger/LogRecord.java
> +    private String host;
Not according to e2e2 tests - https://github.com/PerimeterX/enforcer-specs-tests/blob/dev/utils/schemaValidator/schemas/log_records.json#L17

I'll change in the enforcer specs

2023-12-25 16:08 UTC, EldarHuman commented on src/main/java/com/perimeterx/utils/logger/LogMemory.java
> +            PXClient client = conf.getPxClientInstance();
Not something that I notice.
this function behaves like a single-tone for the pxClientInstance:
<pre lang="no-highlight"><code>
public PXClient getPxClientInstance() throws PXException {
        if (pxClientInstance == null) {
            synchronized (this) {
                if (pxClientInstance == null) {
                    if (this.getPxClient() == null) {
                        pxClientInstance = new PXHttpClient(this);
                    } else {
                        pxClientInstance = this.getPxClient();
                    }
                }
            }
        }
        return pxClientInstance;
    }
</code></pre>

I know it's not the most clean and smooth code but looks thread safe for me. WDYH ?

2023-12-25 16:13 UTC, EldarHuman commented on src/main/java/com/perimeterx/api/PerimeterX.java
> +            }
Seems like we don't have `CORS pre-flight handling` in Java sdk

2023-12-25 16:14 UTC, EldarHuman commented on src/main/java/com/perimeterx/api/PerimeterX.java
> +            }
Changed the order according to your suggestion

2023-12-25 16:19 UTC, EldarHuman commented on src/main/java/com/perimeterx/models/PXContext.java
> +    }
I know and I tried to do some changes in order to make the entire project more testable but it requires a different effort and it's not something to do on the way...

2023-12-25 16:20 UTC, EldarHuman commented on src/main/java/com/perimeterx/models/PXContext.java
> +    }
I consider maybe to take 2-3 days and refactor the entire service so it will be more testable..
If we want to move to DI frameworks it requires more than 3 days.

2023-12-27 17:44 UTC, ori-gold-px approved these changes
Looks good! Just two comments -

(1) The PXContext constructor used only for unit tests is an issue. I approved it right now, but this is something that we should really take care of ASAP.
(2) There are a few logs added into `catch` blocks where the exception is thrown again. If the exception is thrown and logged later, is the added log necessary? If the added log is necessary, should the exception itself be logged as well?

2023-12-27 17:44 UTC, ori-gold-px commented on src/main/java/com/perimeterx/http/PXApacheHttpClient.java
>              throw new RuntimeException(e);
Why adding logs if we're throwing another exception?

2023-12-27 17:44 UTC, ori-gold-px commented on src/main/java/com/perimeterx/utils/logger/LogMemory.java
> +//    private  PXConfiguration config;
Remove comment

2023-12-27 17:44 UTC, ori-gold-px commented on src/main/java/com/perimeterx/models/PXContext.java
> +    }
The solution here is to define an interface `IContext` that the `PXContext` class satisfies. Then, the function signatures that require `PXContext` can instead require `IContext`. This way, the unit tests don't need to use the true `PXContext`, but a different `MockContext` that satisfies `IContext` that can provide the minimum attributes needed to make the unit tests pass.

2023-12-27 17:56 UTC, EldarHuman commented on src/main/java/com/perimeterx/api/activities/BufferedActivityHandler.java
> +                    context.logger.error("failed to send async activities", e);
I think yes.. It can harm our detection

2023-12-27 17:57 UTC, EldarHuman commented on src/main/java/com/perimeterx/utils/logger/LoggerFactory.java
> +    public IPXLogger getLogger(boolean isMemoryEnabled) {
It's more testable. When it's static I can't use mocking

2023-12-27 18:00 UTC, EldarHuman commented on src/main/java/com/perimeterx/http/PXApacheHttpClient.java
>              throw new RuntimeException(e);
We don't print log have in the upper catch blocks

2023-12-27 18:07 UTC, EldarHuman commented
Thanks @ori-gold-px !
I opened a ticket for the Context issue.
[Java SDK](https://perimeterx.atlassian.net/browse/SDKNEW-3389)

2023-12-27 19:09 UTC, ori-gold-px approved these changes

2023-12-27 19:41 UTC, merged