Feature/sdknew 3400 add enforcer name
PerimeterX/perimeterx-java-sdk pull request #352
Opened 2024-01-07 08:57 UTC by EldarHuman

2024-01-07 09:03 UTC, chen-zimmer-px commented on src/main/java/com/perimeterx/utils/logger/LogRecord.java
> +    private String enforcerName = "JavaSDK";
Because of the data annotation, there will be a setter of this member. Is this the only way to add a constant member as an object property?

2024-01-07 09:09 UTC, chen-zimmer-px commented on src/main/java/com/perimeterx/utils/logger/LogRecord.java
> +    private String enforcerName = "JavaSDK";
I think we should change the property name to `module version`?

2024-01-07 09:11 UTC, chen-zimmer-px commented on src/main/java/com/perimeterx/utils/logger/LogRecord.java
> +    private String enforcerName = "JavaSDK";
Please add the SDK version. 
You can use the `SDK_VERSION` constant variable.

2024-01-07 09:13 UTC, chen-zimmer-px requested changes
Please see the comments

2024-01-09 12:55 UTC, OmerBacharPX requested changes

2024-01-09 12:55 UTC, OmerBacharPX commented on src/main/java/com/perimeterx/utils/logger/LogRecord.java
> +import com.perimeterx.utils.Constants;
Why the PR is directly to master?

2024-01-09 13:03 UTC, OmerBacharPX approved these changes

2024-01-09 13:03 UTC, EldarHuman commented on src/main/java/com/perimeterx/utils/logger/LogRecord.java
> +import com.perimeterx.utils.Constants;
Changed

2024-01-09 14:16 UTC, merged