Feature/ci
PerimeterX/perimeterx-java-sdk pull request #359
Opened 2024-02-18 17:33 UTC by guyeisenbach

2024-02-20 15:39 UTC, chen-zimmer-px requested changes
Please change the versions

2024-02-20 15:39 UTC, chen-zimmer-px commented on .github/workflows/ci_e2e.yaml
> +          node-version: '18.x'
20.x

2024-02-20 15:39 UTC, chen-zimmer-px commented on .github/workflows/ci_e2e.yaml
> +        uses: actions/setup-node@v3
v4

2024-02-20 15:39 UTC, chen-zimmer-px commented on .github/workflows/ci_e2e.yaml
> +        uses: actions/checkout@v3
v4

2024-02-20 15:39 UTC, chen-zimmer-px commented on .github/workflows/ci_e2e.yaml
> +      - uses: azure/setup-helm@v3
v4

2024-02-20 15:39 UTC, chen-zimmer-px commented on .github/workflows/ci_e2e.yaml
> +        uses: actions/checkout@v3
v4

2024-02-20 15:39 UTC, chen-zimmer-px commented on .github/workflows/ci_e2e.yaml
> +        uses: actions/checkout@v3
v4

2024-02-20 15:39 UTC, chen-zimmer-px commented on .github/workflows/ci_e2e.yaml
> +        uses: 'google-github-actions/auth@v1'
v2

2024-02-22 13:52 UTC, guyeisenbach commented on .github/workflows/ci_e2e.yaml
> +          node-version: '18.x'
done

2024-02-22 13:52 UTC, guyeisenbach commented on .github/workflows/ci_e2e.yaml
> +        uses: actions/setup-node@v3
done

2024-02-22 13:52 UTC, guyeisenbach commented on .github/workflows/ci_e2e.yaml
> +        uses: actions/checkout@v3
done

2024-02-22 13:53 UTC, guyeisenbach commented on .github/workflows/ci_e2e.yaml
> +        uses: actions/checkout@v3
done

2024-02-22 13:53 UTC, guyeisenbach commented on .github/workflows/ci_e2e.yaml
> +      - uses: azure/setup-helm@v3
done

2024-02-22 13:53 UTC, guyeisenbach commented on .github/workflows/ci_e2e.yaml
> +        uses: actions/checkout@v3
done

2024-02-22 13:53 UTC, guyeisenbach commented on .github/workflows/ci_e2e.yaml
> +        uses: actions/checkout@v3
done

2024-02-22 13:53 UTC, guyeisenbach commented on .github/workflows/ci_e2e.yaml
> +        uses: 'google-github-actions/auth@v1'
done

2024-02-22 15:03 UTC, chen-zimmer-px approved these changes

2024-02-22 15:11 UTC, merged